
CREATE DATABASE IF NOT EXISTS register;

CREATE TABLE  IF NOT EXISTS users (

  id int(11) NOT NULL AUTO_INCREMENT,
  username VARCHAR(50) NOT NULL,
  email VARCHAR(50) NOT NULL,
  password VARCHAR(50) NOT NULL,
  trn_date DATETIME NOT NULL,
  PRIMARY KEY (id)

);
